---

- name: Provision base regolith system
  hosts: all, localhost
  gather_facts: yes

  vars:
    ansible_python_interpreter: /usr/bin/python3
    user:
      name: dana
      group: dana

  pre_tasks:
    - name: Update OS packages
      apt:
        upgrade: dist
        update_cache: yes
        cache_valid_time: 3600
      become: yes
    - name: Create user
      user:
        name: "{{ user.name }}"
        groups: sudo
        append: yes
      become: yes

  roles:
    - role: base
      tags: [base]
      become: yes
    - role: vpn
      tags: [vpn]
      become: yes

  post_tasks:
    - name: Add {{ user.name }} to additional groups
      user:
        name: "{{ user.name }}"
        groups: docker,kvm,libvirt
        append: yes
      become: yes
