---

- name: Provision a workstation
  hosts: localhost

  vars:
    username: dana

  pre_tasks:
    - name: Update OS packages
      apt: upgrade=dist update_cache=yes
      become: yes

  roles:
    - role: base
      become: yes
    - role: vpn
      tags: [vpn]
      become: yes
    - role: kubernetes
      tags: [kubernetes]
      become: yes
    - role: golang
      tags: [golang]
      become: yes
    - role: user
    - role: work
      tags: [work]

  post_tasks:
    - name: Add {{ username }} to docker group
      user: name="{{ username }}" groups=docker append=yes
      become: yes
