---

- name: Provision a workstation
  hosts: all, localhost
  gather_facts: no

  vars:
    ansible_python_interpreter: /usr/bin/python3
    user:
      name: dana
      group: dana
    ubuntu:
      release: cosmic

  pre_tasks:
    - name: Update OS packages
      apt:
        upgrade: dist
        update_cache: yes
        cache_valid_time: 3600
      become: yes
    - name: Create user
      user:
        name: "{{ user.name }}"
        groups: sudo
        append: yes
      become: yes

  roles:
    - role: base
      tags: [base]
      become: yes

    - role: system76
      tags: [system76]
      become: yes

    - role: vpn
      tags: [vpn]
      become: yes

    - role: kubernetes
      tags: [kubernetes]
      become: yes

    - role: user
      tags: [user]
      become: yes
      become_user: "{{ user.name }}"

  post_tasks:
    - name: Add {{ user.name }} to docker group
      user:
        name: "{{ user.name }}"
        groups: docker,kvm,libvirt
        append: yes
      become: yes
