---

- name: Install packages
  apt: name="{{ item }}" state=latest
  with_items:
    - i3
    - pasystray
    - rxvt-unicode
    - xfonts-terminus
    - arandr

- name: Install chrome
  apt: deb="https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb" state=present

- name: Install slack client
  apt: deb="https://downloads.slack-edge.com/linux_releases/slack-desktop-2.3.2-amd64.deb" state=present
