- name: Add PPA for system76
  apt_repository:
    repo: ppa:system76-dev/stable
    state: present
    update_cache: yes

- name: Install system76 packages
  apt:
    state: latest
    name:
      - system76-driver
      - system76-driver-nvidia

- name: Disable annoying HiDPI notification
  shell: |
    gsettings set com.system76.hidpi enable false
  args:
    executable: /bin/bash

- name: displaylink driver dir
  tags: [never]
  file:
    state: directory
    path: /tmp/display-link-driver

- name: Unarchive displaylink driver
  tags: [never]
  unarchive:
    src: display-link-driver.zip
    dest: /tmp/display-link-driver

- name: Run displaylink installer
  tags: [never]
  shell: |
    mv /tmp/display-link-driver/displaylink-driver-* /tmp/display-link-driver/installer.run
    /tmp/display-link-driver/installer.run
  args:
    executable: /bin/bash

- name: Remove displaylink driver dir
  tags: [never]
  file:
    state: absent
    path: /tmp/display-link-driver

- name: Set vconsole font
  tags: [vconsole]
  lineinfile:
    path: /etc/default/console-setup
    regexp: '^FONTFACE='
    line: FONTFACE="Terminus"

- name: Set vconsole font
  tags: [vconsole]
  lineinfile:
    path: /etc/default/console-setup
    regexp: '^FONTSIZE='
    line: FONTSIZE="16x32"
