---

- name: Install NetworkManager dispatch script
  copy:
    src: bin/nm-dispatch-update-dnsmasq
    dest: /etc/NetworkManager/dispatcher.d/vpn-update-dnsmasq
    owner: root
    group: root
    mode: 0755
