---

- name: Install openvpn
  apt: name=openvpn state=latest

- name: Install dnsmasq config
  copy: src=dnsmasq.d/ dest=/etc/NetworkManager/dnsmasq.d/ owner=root group=root

- name: Disable systemd-resolved systemd unit
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: no

- name: Reload network-manager systemd unit
  systemd:
    name: network-manager
    state: reloaded

- name: Installer sudoers config
  copy: src=sudoers.d/ dest=/etc/sudoers.d/ owner=root group=root mode=0440 validate="visudo -cf %s"

- name: Install vpn scripts
  copy: src=bin/ dest=/usr/local/bin/ owner=root group=root mode=0755
