---

- name: Get latest kubectl version
  uri:
    url: https://storage.googleapis.com/kubernetes-release/release/stable.txt
    return_content: yes
  register: kubectl_latest_version

- name: Install kubectl
  get_url:
    url: "http://storage.googleapis.com/kubernetes-release/release/{{ kubectl_latest_version.content | trim }}/bin/linux/amd64/kubectl"
    dest: /usr/local/bin/kubectl
    owner: root
    group: root
    mode: 0755
    force: true

- name: Get latest minikube version
  tags: [minikube]
  uri:
    url: https://api.github.com/repos/kubernetes/minikube/releases/latest
    return_content: yes
  register: minikube_latest_release

- name: Set minikube url
  tags: [minikube]
  set_fact:
    minikube_url: "{{ minikube_latest_release.content | from_json | json_query(query) | first }}"
  vars:
    query: "assets[?name=='minikube-linux-amd64'].browser_download_url"

- name: Install minikube
  tags: [minikube]
  get_url:
    url: "{{ minikube_url }}"
    dest: /usr/local/bin/minikube
    owner: root
    group: root
    mode: 0755
    force: yes

- name: Get latest helm version
  uri:
    url: https://api.github.com/repos/kubernetes/helm/releases/latest
    return_content: yes
  register: helm_latest_release

- name: Set helm version
  set_fact:
    helm_version: "{{ helm_latest_release.content | from_json | json_query('tag_name') }}"

- name: Set helm url
  set_fact:
    helm_url: "https://storage.googleapis.com/kubernetes-helm/helm-{{ helm_version }}-linux-amd64.tar.gz"

- name: Create helm install dir
  file: path=/tmp/helm state=directory

- name: Download helm
  get_url:
    url: "{{ helm_url }}"
    dest: /tmp/helm

- name: Unpack helm
  shell: |
    tar --strip-components=1 -zxpf *.tar.gz
  args:
    chdir: /tmp/helm

- name: Install helm
  copy:
    src: /tmp/helm/helm
    remote_src: yes
    dest: /usr/local/bin/helm
    owner: root
    group: root
    mode: 0755

- name: Remove helm installation files
  file:
    path: /tmp/helm
    state: absent

- name: Install helm-diff plugin
  shell: |
    helm plugin install https://github.com/databus23/helm-diff --version master

- name: Install stern
  tags: [stern]
  get_url:
    url: "https://github.com/wercker/stern/releases/download/1.11.0/stern_linux_amd64"
    dest: /usr/local/bin/stern
    owner: root
    group: root
    mode: 0755

- name: Install argo cli
  get_url:
    url: https://github.com/argoproj/argo/releases/download/v2.3.0/argo-linux-amd64
    dest: /usr/local/bin/argo
    owner: root
    group: root
    mode: 0755
