---

- name: Install basic packages
  apt: name="{{ item }}" state=latest
  with_items:
    - emacs
    - git
    - jq
    - gnupg
    - tmux
    - python-virtualenv
    - openssh-server
    - libssl-dev
    - libreadline-dev
    - zlib1g-dev
