---

- name: Install basic packages
  tags: [packages]
  apt: name="{{ item }}" state=latest
  with_items:
    - emacs
    - git
    - jq
    - gnupg
    - tmux
    - python-virtualenv
    - virtualenvwrapper
    - python-dev
    - openssh-server
    - openvpn
    - laptop-mode-tools
    - apt-transport-https
    - ca-certificates
    - postgresql-client
    - libpq-dev
    - awscli
    - redis-tools
    # for ansible aws
    - python-pip
    - python-boto
    - virtualbox
    - powertop
    - powerline
    - youtube-dl
    - phantomjs
    - nodejs
    - wine-stable
    - shellcheck
    - default-jre
    - sloccount
    - htop
    - traceroute

- name: Install ruby build dependencies
  tags: [ruby, packages]
  apt: name="{{ item }}" state=latest
  with_items:
    - libssl-dev
    - libreadline-dev
    - zlib1g-dev
    - libsqlite3-dev

- name: Install desktop packages
  tags: [packages, desktop]
  apt: name="{{ item }}" state=latest
  with_items:
    - i3
    - pasystray
    - rxvt-unicode
    - xfonts-terminus
    - arandr
    - gimp

- name: Add powerline symbols to terminus font
  tags: [packages, powerline]
  copy: src=11-powerline-symbols-terminus.conf dest=/etc/fonts/conf.d/ owner=root group=root mode=0644

- name: Get latest kubectl version
  tags: [packages, kubernetes]
  command: curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt
  register: kubernetes_version

- name: Install kubectl
  tags: [packages, kubernetes]
  get_url: url="http://storage.googleapis.com/kubernetes-release/release/{{ kubernetes_version.stdout }}/bin/linux/amd64/kubectl" dest=/usr/local/bin/kubectl owner=root group=root mode=0755

- name: Install minikube
  tags: [packages, kubernetes]
  get_url: url=https://storage.googleapis.com/minikube/releases/v0.15.0/minikube-linux-amd64 dest=/usr/local/bin/minikube owner=root group=root mode=0755 force=yes

- name: Check if helm is installed
  tags: [packages, kubernetes, helm]
  stat: path=/usr/local/bin/helm
  register: helm

- name: Create helm install dir
  tags: [helm]
  file: path=/tmp/helm state=directory
  when: helm.stat.exists == false

- name: Download helm
  tags: [packages, kubernetes, helm]
  get_url: url=https://storage.googleapis.com/kubernetes-helm/helm-v2.2.1-linux-amd64.tar.gz dest=/tmp/helm
  when: helm.stat.exists == false

- name: Unpack helm
  tags: [packages, kubernetes, helm]
  shell: |
    tar --strip-components=1 -zxpf *.tar.gz
  args:
    chdir: /tmp/helm
  when: helm.stat.exists == false

- name: Install helm
  tags: [packages, kubernetes, helm]
  copy: src=/tmp/helm/helm remote_src=yes dest=/usr/local/bin/helm owner=root group=root mode=0755
  when: helm.stat.exists == false

- name: Remove helm installation files
  tags: [packages, kubernetes, helm]
  file: path=/tmp/helm state=absent
  when: helm.stat.exists == false

- name: Install chrome
  tags: [packages, desktop]
  apt: deb="https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb" state=present

- name: Install slack client
  tags: [packages, desktop]
  apt: deb="https://downloads.slack-edge.com/linux_releases/slack-desktop-2.3.2-amd64.deb" state=present

- name: Add apt keys for docker
  tags: [packages, docker]
  apt_key: keyserver=hkp://ha.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D

- name: Add apt repository for docker
  tags: [packages, docker]
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-xenial main' state=present update_cache=yes

- name: Install docker
  tags: [packages, docker]
  apt: pkg=docker-engine=1.12* state=present

- name: Install docker-compose
  tags: [packages, docker]
  get_url: url=https://github.com/docker/compose/releases/download/1.9.0/docker-compose-Linux-x86_64  dest=/usr/local/bin/docker-compose owner=root group=root mode=0755

- name: Add sudoers files
  tags: [sudoers]
  copy: src=sudoers.d/ dest=/etc/sudoers.d/ owner=root group=root mode=0440 validate="visudo -cf %s"

- name: Modify nsswitch.conf
  tags: [nsswitch]
  copy: src=nsswitch.conf dest=/etc/ owner=root group=root mode=0644 backup=yes

- name: Install heroku toolbelt
  tags: [heroku]
  shell: wget -O- https://toolbelt.heroku.com/install-ubuntu.sh | sh

- name: Check if hub is installed
  tags: [hub]
  stat: path=/usr/local/bin/hub
  register: hub

- name: Create hub install dir
  tags: [hub]
  file: path=/tmp/hub state=directory
  when: hub.stat.exists == false

- name: Download hub
  tags: [hub]
  get_url: url=https://github.com/github/hub/releases/download/v2.2.9/hub-linux-amd64-2.2.9.tgz dest=/tmp/hub
  when: hub.stat.exists == false

- name: Install hub
  tags: [hub]
  shell: |
    tar --strip-components=1 -zxpf *.tgz
    ./install
  args:
    chdir: /tmp/hub
  when: hub.stat.exists == false

- name: Remove hub installation files
  tags: [hub]
  file: path=/tmp/hub state=absent
  when: hub.stat.exists == false

- name: Install Slackcat
  tags: [slackcat]
  get_url: url=https://github.com/vektorlab/slackcat/releases/download/v1.1/slackcat-1.1-linux-amd64 dest=/usr/local/bin/slackcat owner=root group=root mode=0755

- name: Install lein
  tags: [clojure]
  get_url: url=https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein dest=/usr/local/bin/lein owner=root group=root mode=0755
