---

- name: Install basic packages
  tags: [packages]
  apt: name="{{ item }}" state=latest
  with_items:
    - emacs
    - git
    - jq
    - gnupg
    - tmux
    - python-virtualenv
    - openssh-server
    - openvpn
    - laptop-mode-tools
    - apt-transport-https
    - ca-certificates
    - postgresql-client

- name: Install ruby build dependencies
  tags: [ruby, packages]
  apt: name="{{ item }}" state=latest
  with_items:
    - libssl-dev
    - libreadline-dev
    - zlib1g-dev

- name: Install desktop packages
  tags: [packages, desktop]
  apt: name="{{ item }}" state=latest
  with_items:
    - i3
    - pasystray
    - rxvt-unicode
    - xfonts-terminus
    - arandr

- name: Install chrome
  tags: [packages, desktop]
  apt: deb="https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb" state=present

- name: Install slack client
  tags: [packages, desktop]
  apt: deb="https://downloads.slack-edge.com/linux_releases/slack-desktop-2.3.2-amd64.deb" state=present

- name: Add apt keys for docker
  tags: [packages, docker]
  apt_key: keyserver=hkp://ha.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D

- name: Add apt repository for docker
  tags: [packages, docker]
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-xenial main' state=present update_cache=yes

- name: Install docker
  tags: [packages, docker]
  apt: pkg=docker-engine=1.12* state=present

- name: Install docker-compose
  tags: [packages, docker]
  get_url: url=https://github.com/docker/compose/releases/download/1.9.0/run.sh dest=/usr/local/bin/docker-compose owner=root group=root mode=0755

- name: Add sudoers files
  tags: [sudoers]
  copy: src=sudoers.d/ dest=/etc/sudoers.d/ owner=root group=root mode=0440 validate="visudo -cf %s"

- name: Modify nsswitch.conf
  tags: [nsswitch]
  copy: src=nsswitch.conf dest=/etc/ owner=root group=root mode=0644 backup=yes
