---

- name: Install basic packages
  tags: [packages]
  apt:
    name:
      - autorandr
      - git
      - gnupg
      - tmux
      - python-dev
      - openssh-server
      - openvpn
      - laptop-mode-tools
      - apt-transport-https
      - ca-certificates
      - postgresql-client
      - libpq-dev
      - awscli
      - redis-tools
      # for ansible aws
      - python-pip
      - python-boto
      - python3-venv
      - virtualbox
      - powertop
      - powerline
      - youtube-dl
      - phantomjs
      - nodejs
      - wine-stable
      - default-jre
      - sloccount
      - htop
      - traceroute
      - gnutls-bin
      - xclip
      - ldap-utils
      - moreutils
      - graphviz
      - curl
      - gconf2
      - copyq
      - libffi-dev
    state: latest

- name: Install regolith packages
  tags: [regolith, desktop]
  apt:
    name:
      - i3xrocks-battery
      - i3xrocks-net-traffic
      - i3xrocks-time
      - i3xrocks-cpu-usage
      - i3xrocks-openvpn
      - regolith-look-solarized-dark
      - regolith-compositor-none
      - dunst

- name: Add emacs PPA
  tags: [emacs, packages]
  apt_repository:
    repo: ppa:kelleyk/emacs
    state: present
    update_cache: yes

- name: Install emacs
  tags: [emacs, packages]
  apt:
    name:
      - emacs26

- name: Install ruby build dependencies
  tags: [ruby, packages]
  apt:
    name:
      - libssl-dev
      - libreadline-dev
      - zlib1g-dev
      - libsqlite3-dev
      - cmake
      - libgmp-dev
    state: latest

- name: Install desktop packages
  tags: [packages, desktop]
  apt:
    name:
      - pasystray
      - rxvt-unicode
      - xfonts-terminus
      - arandr
      - gimp
      - maim
      - xautolock
      - blueman
      - firefox
    state: latest

- name: Install playerctl
  tags: [packages, desktop, playerctl]
  apt:
    deb: https://github.com/altdesktop/playerctl/releases/download/v2.1.1/playerctl-2.1.1_amd64.deb
    state: present

- name: Add powerline symbols to terminus font
  tags: [packages, powerline]
  copy:
    src: 11-powerline-symbols-terminus.conf
    dest: /etc/fonts/conf.d/
    owner: root
    group: root
    mode: 0644

- name: Rebuild font cache
  tags: [packages, powerline]
  shell: fc-cache

- name: Install Alacritty
  tags: [packages, desktop, alacritty]
  apt:
    deb: https://github.com/jwilm/alacritty/releases/download/v0.4.0/Alacritty-v0.4.0-ubuntu_18_04_amd64.deb
    state: present

- name: Install jq
  # to get the latest jq, which isn't in the apt repos
  tags: [packages, jq]
  get_url:
    url: https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
    dest: /usr/local/bin/jq
    owner: root
    group: root
    mode: 0755

- name: Check for google chrome apt source
  tags: [packages, desktop, chrome]
  stat:
    path: /etc/apt/sources.list.d/google-chrome.list
  register: chrome_source

- name: Install google chrome
  tags: [packages, desktop, chrome]
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    state: present
  when: not chrome_source.stat.exists

- name: Chrome managed policy dir
  tags: [packages, desktop, chrome]
  file:
    state: directory
    path: /etc/opt/chrome/policies/managed

- name: Add xdg-open policy for google chrome
  tags: [packages, desktop, chrome]
  copy:
    src: chrome-xdg-open-policy.json
    dest: /etc/opt/chrome/policies/managed/xdg-open.json

- name: Check for slack apt source
  stat:
    path: /etc/apt/sources.list.d/slack.list
  register: slack_source

- name: Install slack client
  tags: [packages, desktop, slack]
  apt:
    deb: "https://downloads.slack-edge.com/linux_releases/slack-desktop-{{ slack.version }}-amd64.deb"
    state: present
  when: not slack_source.stat.exists

- name: Add apt keys for spotify
  tags: [packages, desktop, spotify]
  apt_key:
    url: https://download.spotify.com/debian/pubkey.gpg

- name: Add apt repository for spotify
  tags: [packages, desktop, spotify]
  apt_repository:
    repo: "deb http://repository.spotify.com stable non-free"
    state: present
    update_cache: yes

- name: Install spotify
  tags: [packages, desktop, spotify]
  apt:
    pkg: spotify-client
    state: present

- name: Add apt keys for docker
  tags: [packages, docker]
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add apt repository for docker
  tags: [packages, docker]
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ docker_engine.ubuntu_release }} stable"
    state: present
    update_cache: yes

- name: Install docker
  tags: [packages, docker]
  apt:
    pkg: docker-ce
    state: present

- name: Install container-structure-test
  tags: [packages, docker, container-structure-test]
  get_url:
    url: https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64
    dest: /usr/local/bin/container-structure-test
    owner: root
    group: root
    mode: 0755

- name: Add apt keys for gcloud
  tags: [packages, gcloud]
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: Add apt repository for gcloud
  tags: [packages, gcloud]
  apt_repository:
    repo: deb http://packages.cloud.google.com/apt cloud-sdk-{{ ubuntu.release }} main
    state: present
    update_cache: yes

- name: Install gcloud
  tags: [packages, gcloud]
  apt:
    pkg: google-cloud-sdk
    state: present

- name: Add sudoers files
  tags: [sudoers]
  copy:
    src: sudoers.d/
    dest: /etc/sudoers.d/
    owner: root
    group: root
    mode: 0440
    validate: "visudo -cf %s"

- name: Modify nsswitch.conf
  tags: [nsswitch]
  copy:
    src: nsswitch.conf
    dest: /etc/
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: Add apt key for heroku
  tags: [packages, heroku]
  apt_key:
    url: https://cli-assets.heroku.com/apt/release.key

- name: Add apt repository for heroku
  tags: [packages, heroku]
  apt_repository:
    repo: deb https://cli-assets.heroku.com/apt ./
    state: present
    update_cache: yes

- name: Install heroku cli
  tags: [packages, heroku]
  apt:
    pkg: heroku
    state: present

- name: Install Slackcat
  tags: [slackcat]
  get_url:
    url: "https://github.com/bcicen/slackcat/releases/download/v{{ slackcat.version }}/slackcat-{{ slackcat.version }}-linux-amd64"
    dest: /usr/local/bin/slackcat
    owner: root
    group: root
    mode: 0755

- name: Install lein
  tags: [clojure]
  get_url:
    url: https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
    dest: /usr/local/bin/lein
    owner: root
    group: root
    mode: 0755

- name: Install aws-vault
  tags: [aws]
  get_url:
    url: "https://github.com/99designs/aws-vault/releases/download/v{{ aws_vault.version }}/aws-vault-linux-amd64"
    dest: /usr/local/bin/aws-vault
    owner: root
    group: root
    mode: 0755

- name: Install vagrant
  tags: [vagrant]
  apt:
    deb: https://releases.hashicorp.com/vagrant/2.2.7/vagrant_2.2.7_x86_64.deb

- name: Get yj download url
  tags: [yj]
  shell: |
    curl -s https://api.github.com/repos/sclevine/yj/releases/latest \
      | jq -r '.assets[] | select(.name == "yj-linux") | .browser_download_url'
  register: yj_url

- name: Install yj
  tags: [yj]
  get_url:
    url: "{{ yj_url.stdout }}"
    dest: /usr/local/bin/yj
    owner: root
    group: root
    mode: 0755

- name: install DuoConnect
  tags: [duo]
  unarchive:
    src: https://dl.duosecurity.com/DuoConnect-latest.tar.gz
    remote_src: yes
    dest: /usr/local/bin
    owner: root
    group: root
    mode: 0755
    exclude: install.sh

- name: Install zoom client
  tags: [zoom]
  apt: deb=https://zoom.us/client/latest/zoom_amd64.deb state=present
  become: yes
